Repository mini-moment/mimo-server, pull requests merged in 2024-05, with the labels that each got.

#8 TagApi 구현
  src/main/java/com/mimo/server/controller/TagController.java
  src/main/java/com/mimo/server/dao/TagDao.java
  src/main/java/com/mimo/server/dto/TagDto.java
  src/main/java/com/mimo/server/service/TagService.java
  src/main/java/com/mimo/server/service/TagServiceImpl.java
  src/main/resources/mapper/tag.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#9 Feat/map marker
  src/main/java/com/mimo/server/controller/MapController.java
  src/main/java/com/mimo/server/dao/MapDao.java
  src/main/java/com/mimo/server/dto/MapDto.java
  src/main/java/com/mimo/server/service/MapService.java
  src/main/java/com/mimo/server/service/MapServiceImpl.java
  src/main/resources/mapper/map.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#12 Feat/video_service
  .gitignore
  src/main/java/com/mimo/server/MimoServerApplication.java
  src/main/java/com/mimo/server/controller/VideoController.java
  src/main/java/com/mimo/server/error/CustomErrorCode.java
  src/main/java/com/mimo/server/error/ErrorMessage.java
  src/main/java/com/mimo/server/util/MultipartConfig.java
Labels: Feat

#13 InsertPost Api 구현
  src/main/java/com/mimo/server/controller/PostController.java
  src/main/java/com/mimo/server/controller/UserController.java
  src/main/java/com/mimo/server/dao/PostDao.java
  src/main/java/com/mimo/server/dao/UserDao.java
  src/main/java/com/mimo/server/dto/PostDto.java
  src/main/java/com/mimo/server/dto/UserDto.java
  src/main/java/com/mimo/server/service/PostService.java
  src/main/java/com/mimo/server/service/PostServiceImpl.java
  src/main/java/com/mimo/server/service/UserService.java
  src/main/java/com/mimo/server/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/post.xml
  src/main/resources/mapper/user.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#15 HashTag 추가 API
  src/main/java/com/mimo/server/controller/PostController.java
  src/main/java/com/mimo/server/dao/HashTagDao.java
  src/main/java/com/mimo/server/dto/HashTagDto.java
  src/main/java/com/mimo/server/dto/PostDto.java
  src/main/java/com/mimo/server/service/HashTagService.java
  src/main/java/com/mimo/server/service/HashTagServiceImpl.java
  src/main/java/com/mimo/server/service/PostService.java
  src/main/java/com/mimo/server/service/PostServiceImpl.java
  src/main/resources/mapper/hashtag.xml
  src/main/resources/mapper/post.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#18 마커 dto 변경
  src/main/java/com/mimo/server/controller/MapController.java
  src/main/java/com/mimo/server/dao/MapDao.java
  src/main/java/com/mimo/server/dto/MarkerDto.java
  src/main/java/com/mimo/server/service/MapService.java
  src/main/java/com/mimo/server/service/MapServiceImpl.java
  src/main/resources/mapper/map.xml
  src/main/resources/mybatis-config.xml
Labels: Feat

#20 디비 수정 반영 및 mapper 오류 해결
  src/main/java/com/mimo/server/controller/PostController.java
  src/main/java/com/mimo/server/dto/PostDto.java
  src/main/resources/mapper/map.xml
  src/main/resources/mapper/post.xml
  src/main/resources/mapper/user.xml
Labels: Feat, Fix

#21 Video파일 디렉토리 경로 설정 및 VideoController, VideoService 분리
  src/main/java/com/mimo/server/MimoServerApplication.java
  src/main/java/com/mimo/server/controller/VideoController.java
  src/main/java/com/mimo/server/service/VideoService.java
  src/main/java/com/mimo/server/service/VideoServiceImpl.java
  src/main/java/com/mimo/server/util/MultipartConfig.java
  src/main/resources/application.properties
Labels: Feat, Enhance

#23 getPosts API 구현
  src/main/java/com/mimo/server/controller/PostController.java
  src/main/java/com/mimo/server/dao/PostDao.java
  src/main/java/com/mimo/server/dto/PostDto.java
  src/main/java/com/mimo/server/service/PostService.java
  src/main/java/com/mimo/server/service/PostServiceImpl.java
  src/main/resources/mapper/hashtag.xml
  src/main/resources/mapper/post.xml
Labels: Feat
